### ISSUE TITLE
OPENSHIFT DISCOURSE liquidautumn NOT WORKING

### ISSUE THREAD

**Issue by talhaobject90** [liquidautumn/discourse-quickstart#2]
I had tried deploying discourse on openshift through serveral ways but all failed and i got this thread trustable Installing Docker with sudo

But this one too is giving me this error while creating app

I had also tried deploying discourse using liquidautumn through commandline, i had changed the vestalversions repo to another working one, but there are still many issues while deploying.

Later i tried this repo https://github.com/NeilBryant/discourse-quickstart-neb

But unfortunately went through version issues,

All these repo are updated at least 2 years ago

Could some one refer me any working repo or article to easily deploy discourse over openshift, or if any of these repo contributors went through this question, please figure out what's wrong with the repo code.

![](http://i.stack.imgur.com/Qb7rW.png)

**Comment by v998** [comment]
it's a long time FACT...
now you know?
it's too late...

**Comment by liquidautumn** [comment]
I bet there's a lot changed in the API through the course of 2 years, if you really need this working you'll have to track the problems down by yourself and maybe send pull request.
I'd recommend going Docker route, ie https://github.com/discourse/discourse_docker is quite active and can be run over one of Docker cartridges I believe exist.
